[server]
"port" = 10602

[mysql]
"username" = "root"
"password" = "king"
"host" = "127.0.0.1:3306"
"ahmddb" = "test"
"proxydb" = "proxy_server"

[proxyserver]
"ip" = "10.1.202.250"

[accounts]
[accounts.admin]
"user" = "admin"
"pwd" = "admin"

[accounts.flk]
"user" = "flk"
"pwd" = "comlink"
